// Currency code -> flag emoji + symbol, for the ~30 ECB/Frankfurter currencies.
export const META = {
  AUD: { flag: '🇦🇺', symbol: '$' },
  BGN: { flag: '🇧🇬', symbol: 'лв' },
  BRL: { flag: '🇧🇷', symbol: 'R$' },
  CAD: { flag: '🇨🇦', symbol: '$' },
  CHF: { flag: '🇨🇭', symbol: 'Fr' },
  CNY: { flag: '🇨🇳', symbol: '¥' },
  CZK: { flag: '🇨🇿', symbol: 'Kč' },
  DKK: { flag: '🇩🇰', symbol: 'kr' },
  EUR: { flag: '🇪🇺', symbol: '€' },
  GBP: { flag: '🇬🇧', symbol: '£' },
  HKD: { flag: '🇭🇰', symbol: '$' },
  HUF: { flag: '🇭🇺', symbol: 'Ft' },
  IDR: { flag: '🇮🇩', symbol: 'Rp' },
  ILS: { flag: '🇮🇱', symbol: '₪' },
  INR: { flag: '🇮🇳', symbol: '₹' },
  ISK: { flag: '🇮🇸', symbol: 'kr' },
  JPY: { flag: '🇯🇵', symbol: '¥' },
  KRW: { flag: '🇰🇷', symbol: '₩' },
  MXN: { flag: '🇲🇽', symbol: '$' },
  MYR: { flag: '🇲🇾', symbol: 'RM' },
  NOK: { flag: '🇳🇴', symbol: 'kr' },
  NZD: { flag: '🇳🇿', symbol: '$' },
  PHP: { flag: '🇵🇭', symbol: '₱' },
  PLN: { flag: '🇵🇱', symbol: 'zł' },
  RON: { flag: '🇷🇴', symbol: 'lei' },
  SEK: { flag: '🇸🇪', symbol: 'kr' },
  SGD: { flag: '🇸🇬', symbol: '$' },
  THB: { flag: '🇹🇭', symbol: '฿' },
  TRY: { flag: '🇹🇷', symbol: '₺' },
  USD: { flag: '🇺🇸', symbol: '$' },
  ZAR: { flag: '🇿🇦', symbol: 'R' },
}

export const metaFor = (code) => META[code] || { flag: '🏳️', symbol: '' }
